import pandas as pd
import streamlit as st

@st.cache_data
def clean_data(df):
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*NIKAH.*$)', 'PERNIKAHAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*HAMIL.*$)', 'HAMIL', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KONTRAK.*$)', 'KONTRAK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*EFISIENSI.*$)', 'EFISIENSI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENGURANGAN.*$)', 'EFISIENSI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SAKIT.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*BEDREST.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OPERASI.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ISTIRAHAT.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KESEHATAN.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OBAT.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*FISIK.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KURANG SEHAT.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KECELAKAAN.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TREATMENT.*$)', 'SAKIT', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KABUR.*$)', 'MANGKIR', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MANGKIR.*$)', 'MANGKIR', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK MASUK.*$)', 'MANGKIR', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK ADA KABAR.*$)', 'MANGKIR', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*COVID.*$)', 'COVID19', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KELUARGA.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ACHIVE TARGET.*$)', 'TIDAK ACHIEVE TARGET', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TARGET.*$)', 'TIDAK ACHIEVE TARGET', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TAGRE.*$)', 'TIDAK ACHIEVE TARGET', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TERMINATE.*$)', 'TERMINASI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERFORM.*$)', 'PERFORMANCE KURANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*DEMOSI.*$)', 'PERFORMANCE KURANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MENINGGAL.*$)', 'MENINGGAL', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ANAK.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SUAMI.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ISTRI.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ORANG TUA.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ORTU.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*IBU.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*FAMILY.*$)', 'KELUARGA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*GAJI.*$)', 'GAJI/BAYARAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PAY.*$)', 'GAJI/BAYARAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PEKERJAAN.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PINDAH.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OPPORTUNITY.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MEDAN.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*USAHA.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*COMPANY LAMA.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENGALAMAN BARU.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KERJAAN BARU.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PEKERJAAN BARU.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OFFERING.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OFFER.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MUTASI.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MENETAP.*$)', 'PINDAH KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MAKASSAR.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*S2.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*S1.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KULIAH.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SEKOLAH.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*STUDY.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KAMPUS.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENDIDIKAN.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*DOSEN.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SEMESTER.*$)', 'PENDIDIKAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*BERHIJAB.*$)', 'KEAGAMAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*BERHIJAB.*$)', 'KEAGAMAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*RIBUT.*$)', 'PERTENGKARAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*BERANTEM.*$)', 'PERTENGKARAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*LINGKUNGAN.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SUASANA.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TEKANAN.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SUPPORT.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*CULTURE.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*DIHARGAI.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK COCOK.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SISTEM KERJA.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*FORMAT BISNIS.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERUBAHAN STRUKTUR.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*BM.*$)', 'LINGKUNGAN PEKERJAAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*JAM.*$)', 'WAKTU KERJA', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SP3.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SP 3.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*NYOLONG.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*LARANGAN.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MANIPULASI.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KASUS.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*transfer.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*FRAUD.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*FRAUD MENCURI UANG.*$)', 'KASUS', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*LOKASI.*$)', 'JARAK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*JARAK.*$)', 'JARAK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*JAUH.*$)', 'JARAK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*VISIT.*$)', 'JARAK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MAGANG.*$)', 'SELESAI MAGANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*SERING TERLAMBAT.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PRODUKTIF.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK SANGGUP.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*ATTITUDE.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KINERJA.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*OMSET.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KOMPLAIN.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*INTEGRITAS.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KOMITMEN.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KESALAHAN.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERFORMANCE.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*EXCEL.*$)', 'PERFORMANCE', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KEPERLUAN.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*CERAI.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERSONAL.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PRIBADI.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENJUALAN TANAH.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PULANG KAMPUNG.*$)', 'KEPENTINGAN PRIBADI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TRAINING.*$)', 'TRAINING', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*EVALUASI.*$)', 'TIDAK PERPANJANG EVALUASI', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK DIPERPANJANG.*$)', 'TIDAK PERPANJANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*KEMITRAAN.*$)', 'TIDAK PERPANJANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TIDAK DILANJUTKAN.*$)', 'TIDAK PERPANJANG', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*RESIGN.*$)', 'RESIGN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENGUNDURAN DIRI.*$)', 'RESIGN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PENGAJUAN.*$)', 'RESIGN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERNYATAAN.*$)', 'RESIGN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*MELANJUTKAN.*$)', 'RESIGN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PEMUTUSAN HUBUNGAN KERJA.*$)', 'PHK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*CUT.*$)', 'PHK', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*DAILY WORKER.*$)', 'DAILY WORKER', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*PERBANTUAN.*$)', 'DAILY WORKER', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*nan.*$)', 'TANPA KETERANGAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TANPA KETERANGAN  *$)', 'TANPA KETERANGAN', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].str.replace(r'(^.*TANPA KETERANGAN  *$)', 'TANPA KETERANGAN', regex=True)
    df['PAKLARING'] = df['PAKLARING'].str.replace(r'(^.*no.*$)', 'NO', regex=True)
    df['ALASAN RESIGN'] = df['ALASAN RESIGN'].fillna("TANPA KETERANGAN")
    df["PAKLARING"] = df["PAKLARING"].fillna("TIDAK TAHU")
    df["PLACEMENT"] = df["PLACEMENT"].fillna("TIDAK TAHU")
    df = df.dropna(subset=['MASA KERJA'])
    df = df.drop(df[df['ALASAN RESIGN'] == 'TANPA KETERANGAN'].index)
    return df